import helpers.fakeGemini
import helpers.gemini
import models.battle
import random


from fastapi import APIRouter, Depends, HTTPException
from fastapi import Request
from fastapi import Query
from fastapi import Body

import re

router = APIRouter(
    prefix='/battle',
    tags=['battle']
)
'''
Generate a full quiz based on a given topic for battle mode.
Parameters:
- topic: str (the subject of the quiz)
Returns:
- quiz: str (the full quiz text generated by Gemini)
'''
@router.get("/generateQuiz", response_model=models.battle.get_quiz_generation_request)
async def generate_quiz(request: Request, 
        topic: str = Query(..., description="The subject of the quiz", )
):
    '''
    Generate a full quiz based on a given topic for battle mode.
    '''
    
    raw_quiz = helpers.gemini.geminiGeneratesFullQuiz(topic)
    
    if not raw_quiz or not raw_quiz.text:
        raise HTTPException(status_code=500, detail="Failed to generate quiz")
    
    return {
        "quiz": raw_quiz.text
    }



'''
Generate a question for a quiz.
Parameters: 
- quiz: str (the full quiz text generated by Gemini)
- difficulty: int (the difficulty level of the question, from 1 to 5)
Returns:
- question: str
- options: dict (e.g., {"A": "Option A", "B": "Option B", "C": "Option C", "D": "Option D"})
- correct_answer: str (e.g., "A", "B", "C", "D")

Now uses real gemini instead of fakeGemini.  
'''
@router.post("/generateQuestion", response_model=models.battle.get_battle_question_response)
async def get_battle_question(
    quiz: str = Body(...), 
    difficulty: int = Body(...)
):
    '''
    Generate a question for a quiz.
    '''
    raw_text = helpers.gemini.generateQuizQuestion(quiz, difficulty)
    if(raw_text == None):
        print(f"DEBUG: Gemini returned nothing {raw_text}")
        raise HTTPException(status_code=400, detail="Invalid question format")
    raw_text = raw_text.strip()
    
    # Regex to get the question, options, and correct answer from the raw text
    pattern = (
        r"Question:\s*(?P<question>.*?)\s+"
        r"A\.\s*(?P<A>.*?)\s+"
        r"B\.\s*(?P<B>.*?)\s+"
        r"C\.\s*(?P<C>.*?)\s+"
        r"D\.\s*(?P<D>.*?)\s+"
        r"Correct Answer:\s*(?P<Answer>.*)"
    )
    
    match = re.search(pattern, raw_text, re.DOTALL | re.IGNORECASE)
    
    if not match:
        # If matching failed
        print(f"DEBUG: Failed to match this text: {raw_text}")
        raise HTTPException(status_code=400, detail="Invalid question format")
        
    return {
    "question": match.group("question").strip(),
    "A": match.group("A").strip(),
    "B": match.group("B").strip(),
    "C": match.group("C").strip(),
    "D": match.group("D").strip(),
    "Answer": match.group("Answer").strip()[-1]
}

'''
Submit an answer for battle mode and calculate HP changes.
Parameters:
- answer: str (the user's selected answer)
- correctAnswer: str (the correct answer)
- playerHP: int (the player's current HP)
- enemyHP: int (the enemy's current HP)
- questionsRight: int (the number of questions the player has gotten right in a row)
- questionsWrong: int (the number of questions the player has gotten wrong in a row)
- difficulty: int (the current difficulty level)
- damageMultiplier: float (the current damage multiplier based on if an item has been used)
Returns:
- result: str (either "correct" or "wrong")
- playerHP: int (the player's updated HP)
- enemyHP: int (the enemy's updated HP)
'''
@router.post("/hpAnswerChange", response_model=models.battle.submit_battle_answer_response)
async def submit_battle_answer(data: models.battle.submit_battle_answer_request):
    '''
    Calculate HP changes based on the user's answer.
    '''

    selected = data.answer
    correct = data.correctAnswer
    player_hp = data.playerHP
    enemy_hp = data.enemyHP
    questions_right = data.questionsRight
    questions_wrong = data.questionsWrong
    difficulty = data.difficulty
    damage_multiplier = data.damageMultiplier

    if selected is None or correct is None:
        raise HTTPException(status_code=400, detail="Missing data")

    crit_hit = False
    if selected == correct:
        if(random.random() < 0.1):
            enemy_hp -= 20 * damage_multiplier
            crit_hit = True
            result = "correct"
            questions_right += 1
            questions_wrong = 0
            if(questions_right == 2 and difficulty < 5):
                difficulty += 1
                questions_right = 0
        else:
            enemy_hp -= 10 * damage_multiplier
            result = "correct"
            questions_right += 1
            questions_wrong = 0
            if(questions_right == 2 and difficulty < 5):
                difficulty += 1
                questions_right = 0
    else:
        if(random.random() < 0.1):
            player_hp -= 20
            crit_hit = True
            result = "wrong"
            questions_wrong += 1
            questions_right = 0
            if(questions_wrong == 2 and difficulty > 1):
                difficulty -= 1
                questions_wrong = 0
        else:
            player_hp -= 10 
            result = "wrong"
            questions_wrong += 1
            questions_right = 0
            if(questions_wrong == 2 and difficulty > 1):
                difficulty -= 1
                questions_wrong = 0

    return {
        "result": result,
        "playerHP": player_hp,
        "enemyHP": enemy_hp,
        "difficulty": difficulty,
        "critHit": crit_hit,
        "questionsRight": questions_right,
        "questionsWrong": questions_wrong,
        "damageMultiplier": damage_multiplier
    }

'''Use an item during battle mode and calculate its effects.
Parameters:
- itemName: str (the name of the item being used)
- playerHP: int (the player's current HP)
- enemyHP: int (the enemy's current HP)
- damageMultiplier: float (the current damage multiplier based on if an item has been used)
Returns:
- result: str (a message indicating the item was used successfully)
- playerHP: int (the player's updated HP)
- enemyHP: int (the enemy's updated HP)
- damageMultiplier: float (the updated damage multiplier)
'''

@router.post("/useItem", response_model=models.battle.use_item_response)
async def use_item(data: models.battle.use_item_request):
    '''
    Use an item during battle mode and calculate its effects.
    '''
    item_name = data.itemName
    player_hp = data.playerHP
    enemy_hp = data.enemyHP
    damage_multiplier = data.damageMultiplier

    if item_name is None:
        raise HTTPException(status_code=400, detail="Missing item name")

    if item_name == "Mini Shield":
        player_hp += 10
        if player_hp > 100:
            player_hp = 100
    elif item_name == "Big Shield":
        player_hp += 20
        if player_hp > 100:
            player_hp = 100
    elif item_name == "Chug Jug":
        player_hp += 50
        if player_hp > 100:
            player_hp = 100
    elif item_name == "Damage Boost":
        damage_multiplier = 2.0
    elif item_name == "Damage Mega Boost":
        damage_multiplier = 3.0
    elif item_name == "Damage Ultra Boost":
        damage_multiplier = 4.0
    elif item_name == "Small Hint" or item_name == "Big Hint":
        # Hints are handled on the frontend, so we don't need to do anything here
        pass
        
    else:
        raise HTTPException(status_code=400, detail="Invalid item name")

    return {
        "result": "Item used successfully",
        "playerHP": player_hp,
        "enemyHP": enemy_hp,
        "damageMultiplier": damage_multiplier
    }