[pytest]
# Tell pytest to look in these folders
testpaths = backend-tests
# Tell pytest that your files might end in _tests.py (plural)
python_files = *_tests.py test_*.py
# Add the root to the python path so 'import backend' works
pythonpath = .